# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dezrez"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Olivier Kouame"]
  s.date = "2012-02-04"
  s.description = "Integration tools for Diamond Residential and dezrez.com"
  s.email = "olivier.kouame@gmail.com"
  s.executables = ["dezrez"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".idea/.rakeTasks",
    ".idea/dezrez.iml",
    ".idea/encodings.xml",
    ".idea/inspectionProfiles/Project_Default.xml",
    ".idea/inspectionProfiles/profiles_settings.xml",
    ".idea/misc.xml",
    ".idea/modules.xml",
    ".idea/vcs.xml",
    ".idea/workspace.xml",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/dezrez",
    "config/database.yml",
    "config/settings.yml",
    "dezrez.gemspec",
    "lib/dezrez.rb",
    "lib/dezrez/feed.rb",
    "lib/dezrez/photo.rb",
    "lib/dezrez/portals.rb",
    "lib/dezrez/post.rb",
    "lib/dezrez/post_meta.rb",
    "lib/dezrez/property.rb",
    "lib/dezrez/property_parser.rb",
    "lib/dezrez/subscriber.rb",
    "lib/dezrez/version.rb",
    "spec/fixtures/all_results.xml",
    "spec/fixtures/photos/1022444.1.jpg",
    "spec/fixtures/photos/1022444.2.jpg",
    "spec/fixtures/photos/1022444.3.jpg",
    "spec/fixtures/photos/1022444.4.jpg",
    "spec/fixtures/photos/1022444.5.jpg",
    "spec/fixtures/photos/1062005.1.jpg",
    "spec/fixtures/photos/1062005.2.jpg",
    "spec/fixtures/photos/1062005.3.jpg",
    "spec/fixtures/photos/1062005.4.jpg",
    "spec/fixtures/photos/1217869.1.jpg",
    "spec/fixtures/photos/1217869.2.jpg",
    "spec/fixtures/photos/1217869.3.jpg",
    "spec/fixtures/photos/1217869.4.jpg",
    "spec/fixtures/photos/1217869.5.jpg",
    "spec/fixtures/photos/1217869.6.jpg",
    "spec/fixtures/photos/1217869.7.jpg",
    "spec/fixtures/photos/1345636.1.jpg",
    "spec/fixtures/photos/1345636.2.jpg",
    "spec/fixtures/photos/1345636.3.jpg",
    "spec/fixtures/photos/1345636.4.jpg",
    "spec/fixtures/photos/1345636.5.jpg",
    "spec/fixtures/photos/1345636.6.jpg",
    "spec/fixtures/photos/1345636.7.jpg",
    "spec/fixtures/photos/1345636.8.jpg",
    "spec/fixtures/photos/1345636.9.jpg",
    "spec/fixtures/photos/1348309.1.jpg",
    "spec/fixtures/photos/1348309.2.jpg",
    "spec/fixtures/photos/1348309.4.jpg",
    "spec/fixtures/photos/1348309.5.jpg",
    "spec/fixtures/photos/1348309.6.jpg",
    "spec/fixtures/photos/1348309.7.jpg",
    "spec/fixtures/photos/1348309.8.jpg",
    "spec/fixtures/photos/1352310.1.jpg",
    "spec/fixtures/photos/1352310.10.jpg",
    "spec/fixtures/photos/1352310.2.jpg",
    "spec/fixtures/photos/1352310.3.jpg",
    "spec/fixtures/photos/1352310.4.jpg",
    "spec/fixtures/photos/1352310.5.jpg",
    "spec/fixtures/photos/1352310.6.jpg",
    "spec/fixtures/photos/1352310.7.jpg",
    "spec/fixtures/photos/1352310.8.jpg",
    "spec/fixtures/photos/1404958.1.jpg",
    "spec/fixtures/photos/1404958.2.jpg",
    "spec/fixtures/photos/1404958.3.jpg",
    "spec/fixtures/photos/1404958.4.jpg",
    "spec/fixtures/photos/1404958.5.jpg",
    "spec/fixtures/photos/1425711.1.jpg",
    "spec/fixtures/photos/1425711.10.jpg",
    "spec/fixtures/photos/1425711.12.jpg",
    "spec/fixtures/photos/1425711.2.jpg",
    "spec/fixtures/photos/1425711.3.jpg",
    "spec/fixtures/photos/1425711.4.jpg",
    "spec/fixtures/photos/1425711.5.jpg",
    "spec/fixtures/photos/1425711.6.jpg",
    "spec/fixtures/photos/1425711.7.jpg",
    "spec/fixtures/photos/1425711.8.jpg",
    "spec/fixtures/photos/1425711.9.jpg",
    "spec/fixtures/photos/1657526.1.jpg",
    "spec/fixtures/photos/1657526.2.jpg",
    "spec/fixtures/photos/1657526.3.jpg",
    "spec/fixtures/photos/1657526.4.jpg",
    "spec/fixtures/photos/1657526.5.jpg",
    "spec/fixtures/photos/1680978.1.jpg",
    "spec/fixtures/photos/1680978.2.jpg",
    "spec/fixtures/photos/1680978.3.jpg",
    "spec/fixtures/photos/1680978.4.jpg",
    "spec/fixtures/photos/1680978.5.jpg",
    "spec/fixtures/photos/1680980.1.jpg",
    "spec/fixtures/photos/1680980.10.jpg",
    "spec/fixtures/photos/1680980.2.jpg",
    "spec/fixtures/photos/1680980.3.jpg",
    "spec/fixtures/photos/1680980.4.jpg",
    "spec/fixtures/photos/1680980.5.jpg",
    "spec/fixtures/photos/1680985.1.jpg",
    "spec/fixtures/photos/1680985.2.jpg",
    "spec/fixtures/photos/1680985.3.jpg",
    "spec/fixtures/photos/1680985.4.jpg",
    "spec/fixtures/photos/1680985.5.jpg",
    "spec/fixtures/photos/1680985.8.jpg",
    "spec/fixtures/photos/1913558.1.jpg",
    "spec/fixtures/photos/1913558.2.jpg",
    "spec/fixtures/photos/1913558.3.jpg",
    "spec/fixtures/photos/1913558.4.jpg",
    "spec/fixtures/photos/1913558.6.jpg",
    "spec/fixtures/photos/1919875.1.jpg",
    "spec/fixtures/photos/1919875.2.jpg",
    "spec/fixtures/photos/1919875.3.jpg",
    "spec/fixtures/photos/1919875.4.jpg",
    "spec/fixtures/photos/1919875.5.jpg",
    "spec/fixtures/photos/2069973.1.jpg",
    "spec/fixtures/photos/2069973.2.jpg",
    "spec/fixtures/photos/2069973.3.jpg",
    "spec/fixtures/photos/2069973.4.jpg",
    "spec/fixtures/photos/2069973.5.jpg",
    "spec/fixtures/photos/2069973.6.jpg",
    "spec/fixtures/photos/2227293.1.jpg",
    "spec/fixtures/photos/2227293.2.jpg",
    "spec/fixtures/photos/2227293.3.jpg",
    "spec/fixtures/photos/2227293.4.jpg",
    "spec/fixtures/photos/2227293.5.jpg",
    "spec/fixtures/photos/2227293.6.jpg",
    "spec/fixtures/photos/258204.1.jpg",
    "spec/fixtures/photos/258204.2.jpg",
    "spec/fixtures/photos/258204.3.jpg",
    "spec/fixtures/photos/258204.4.jpg",
    "spec/fixtures/photos/258204.5.jpg",
    "spec/fixtures/photos/262452.1.jpg",
    "spec/fixtures/photos/262452.2.jpg",
    "spec/fixtures/photos/262452.3.jpg",
    "spec/fixtures/photos/262452.4.jpg",
    "spec/fixtures/photos/262452.5.jpg",
    "spec/fixtures/photos/393772.1.jpg",
    "spec/fixtures/photos/393772.2.jpg",
    "spec/fixtures/photos/393772.3.jpg",
    "spec/fixtures/photos/393772.4.jpg",
    "spec/fixtures/photos/393772.5.jpg",
    "spec/fixtures/photos/415010.1.jpg",
    "spec/fixtures/photos/415010.2.jpg",
    "spec/fixtures/photos/415010.3.jpg",
    "spec/fixtures/photos/415010.4.jpg",
    "spec/fixtures/photos/462648.1.jpg",
    "spec/fixtures/photos/462648.10.jpg",
    "spec/fixtures/photos/462648.2.jpg",
    "spec/fixtures/photos/462648.3.jpg",
    "spec/fixtures/photos/462648.4.jpg",
    "spec/fixtures/photos/462648.5.jpg",
    "spec/fixtures/photos/800836.1.jpg",
    "spec/fixtures/photos/800836.2.jpg",
    "spec/fixtures/photos/800836.3.jpg",
    "spec/fixtures/photos/800836.4.jpg",
    "spec/fixtures/photos/800836.5.jpg",
    "spec/fixtures/photos/800836.6.jpg",
    "spec/fixtures/photos/800836.8.jpg",
    "spec/fixtures/photos/800836.9.jpg",
    "spec/fixtures/photos/801408.1.jpg",
    "spec/fixtures/photos/801408.2.jpg",
    "spec/fixtures/photos/801408.3.jpg",
    "spec/fixtures/photos/801408.4.jpg",
    "spec/fixtures/photos/801408.5.jpg",
    "spec/fixtures/photos/801408.6.jpg",
    "spec/fixtures/photos/801408.8.jpg",
    "spec/fixtures/photos/801408.9.jpg",
    "spec/fixtures/photos/862250.1.jpg",
    "spec/fixtures/photos/862250.3.jpg",
    "spec/fixtures/photos/862250.4.jpg",
    "spec/fixtures/photos/862250.5.jpg",
    "spec/fixtures/photos/862250.6.jpg",
    "spec/fixtures/photos/871282.1.jpg",
    "spec/fixtures/photos/871282.2.jpg",
    "spec/fixtures/photos/871282.3.jpg",
    "spec/fixtures/photos/871282.4.jpg",
    "spec/fixtures/photos/968301.1.jpg",
    "spec/fixtures/photos/968301.2.jpg",
    "spec/fixtures/photos/968301.3.jpg",
    "spec/fixtures/photos/968301.4.jpg",
    "spec/fixtures/photos/968301.5.jpg",
    "spec/fixtures/photos/968301.6.jpg",
    "spec/fixtures/properties/1022444.xml",
    "spec/fixtures/properties/1062005.xml",
    "spec/fixtures/properties/1217869.xml",
    "spec/fixtures/properties/1345636.xml",
    "spec/fixtures/properties/1348309.xml",
    "spec/fixtures/properties/1352310.xml",
    "spec/fixtures/properties/1404958.xml",
    "spec/fixtures/properties/1425711.xml",
    "spec/fixtures/properties/1657526.xml",
    "spec/fixtures/properties/1680978.xml",
    "spec/fixtures/properties/1680980.xml",
    "spec/fixtures/properties/1680985.xml",
    "spec/fixtures/properties/1913558.xml",
    "spec/fixtures/properties/1919875.xml",
    "spec/fixtures/properties/2069973.xml",
    "spec/fixtures/properties/2227293.xml",
    "spec/fixtures/properties/258204.xml",
    "spec/fixtures/properties/262452.xml",
    "spec/fixtures/properties/393772.xml",
    "spec/fixtures/properties/415010.xml",
    "spec/fixtures/properties/462648.xml",
    "spec/fixtures/properties/800836.xml",
    "spec/fixtures/properties/801408.xml",
    "spec/fixtures/properties/862250.xml",
    "spec/fixtures/properties/871282.xml",
    "spec/fixtures/properties/968301.xml",
    "spec/fixtures/real/all_results.xml",
    "spec/fixtures/real/properties/2432973.xml",
    "spec/fixtures/real/properties/2434681.xml",
    "spec/fixtures/real/properties/2435833.xml",
    "spec/fixtures/real/properties/2436023.xml",
    "spec/fixtures/real/properties/2436491.xml",
    "spec/fixtures/real/properties/2436529.xml",
    "spec/fixtures/real/properties/2436584.xml",
    "spec/fixtures/real/properties/2436673.xml",
    "spec/fixtures/real/properties/2436957.xml",
    "spec/fixtures/real/properties/2438301.xml",
    "spec/fixtures/real/properties/2438422.xml",
    "spec/fixtures/real/properties/2440292.xml",
    "spec/fixtures/real/properties/2440573.xml",
    "spec/fixtures/real/properties/2440608.xml",
    "spec/fixtures/real/properties/2440666.xml",
    "spec/fixtures/real/properties/2440715.xml",
    "spec/fixtures/real/properties/2440772.xml",
    "spec/fixtures/real/properties/2440887.xml",
    "spec/models/photo_spec.rb",
    "spec/models/portals_spec.rb",
    "spec/models/post_spec.rb",
    "spec/models/property_parser_spec.rb",
    "spec/models/property_spec.rb",
    "spec/models/subscriber_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/okouam/dezrez"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Integration tools for Diamond Residential and dezrez.com"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<logging>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<logging>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<logging>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

