development:
  adapter: mysql2
  host: localhost
  password: xxxxxxxxxx
  username: xxxxxxxxxxxxxxxxx
  database: xxxxxxxxxxxxxxxxxxxxx

test:
  adapter: mysql2
  host: localhost
  password: xxxxxxxxxxx
  username: xxxxxxxxxxxxxxxxxxxxx
  database: xxxxxxxxxxxxxxxxxxxxxxxxx

production:
  adapter: mysql2
  host: xxxxxxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxx
  username: xxxxxxxxxxxxxxxxxxxxxx
  database: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
