production:
  website: http://diamondresidential.codeifier.com
  image_directory: /home/deployment/sites/diamondresidential/wp-content/uploads
  portals:
    zoopla:
      username: xxxxxxxxxxx
      password: xxxxxxxxxx
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: xxxxxxxxxxxxxxxx
      password:  xxxxxxxxxxxxxx
      branch_id: 51272
      url: ftp.primelocation.com

development:
  website: http://diamondresidential.local
  image_directory: /tmp
  portals:
    zoopla:
      username: xxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxxxxx
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: xxxxxxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxxxx
      branch_id: 51272
      url: ftp.primelocation.com
