production:
  website: http://diamondresidential.codeifier.com
  image_directory: /home/deployment/sites/diamondresidential/wp-content/uploads
  portals:
    zoopla:
      username: diamond
      password: tpFqD9qd56R7
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: diamond
      password:  tpFqD9qd56R7
      branch_id: 57608
      url: ftp.findaproperty.com

development:
  website: http://diamondresidential.local
  image_directory: /tmp
  portals:
    zoopla:
      username: diamond
      password: tpFqD9qd56R7
      branch_id: 34134
      url: ftp.zoopla.com
    findaproperty:
      username: diamond
      password: tpFqD9qd56R7
      branch_id: 57608
      url: ftp.findaproperty.com
